# Generated by Django 6.0.6 on 2026-07-05 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('zone_type', models.CharField(choices=[('safe', 'Safe Zone'), ('danger', 'Danger Zone'), ('custom', 'Custom Zone')], default='custom', max_length=20)),
                ('center_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('center_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_meters', models.PositiveIntegerField(default=250)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enter', 'Enter'), ('exit', 'Exit')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='geofencing.geofence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='geofence',
            index=models.Index(fields=['zone_type', 'is_active'], name='geofencing__zone_ty_ea0e78_idx'),
        ),
        migrations.AddIndex(
            model_name='geofence',
            index=models.Index(fields=['owner', 'is_active'], name='geofencing__owner_i_08bc01_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['user', 'occurred_at'], name='geofencing__user_id_afe45c_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['geofence', 'occurred_at'], name='geofencing__geofenc_afcf2f_idx'),
        ),
    ]
