# Generated by Django 6.0.6 on 2026-07-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('provider', models.CharField(choices=[('google_maps', 'Google Maps'), ('mapbox', 'Mapbox'), ('openstreetmap', 'OpenStreetMap')], max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_routing', models.BooleanField(default=True)),
                ('supports_traffic', models.BooleanField(default=False)),
                ('supports_places', models.BooleanField(default=False)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
