# Generated by Django 6.0.6 on 2026-07-05 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('other', 'Other')], default='other', max_length=30)),
                ('fcm_token', models.TextField(blank=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('network_type', models.CharField(blank=True, max_length=50)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='devices_dev_user_id_de7ec5_idx'), models.Index(fields=['device_id'], name='devices_dev_device__e2c19e_idx'), models.Index(fields=['last_seen_at'], name='devices_dev_last_se_c75af6_idx')],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
