# Generated by Django 6.0.6 on 2026-07-05 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('responder', 'Responder'), ('organization', 'Organization')], default='family', max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('can_view_live_location', models.BooleanField(default=True)),
                ('can_view_route_history', models.BooleanField(default=True)),
                ('can_view_battery', models.BooleanField(default=True)),
                ('can_view_medical_info', models.BooleanField(default=False)),
                ('can_receive_sos', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['owner', 'role'], name='contacts_tr_owner_i_93e68d_idx'), models.Index(fields=['phone'], name='contacts_tr_phone_158601_idx')],
                'unique_together': {('owner', 'phone')},
            },
        ),
    ]
