# Generated by Django 6.0.6 on 2026-07-05 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('key_prefix', models.CharField(db_index=True, max_length=16)),
                ('hashed_key', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('emergency', models.BooleanField(db_index=True, default=False)),
                ('public_share_token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('latest_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('latest_accuracy', models.FloatField(blank=True, null=True)),
                ('latest_speed', models.FloatField(blank=True, null=True)),
                ('latest_heading', models.FloatField(blank=True, null=True)),
                ('latest_altitude', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('network_type', models.CharField(blank=True, max_length=50)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='tracking.trackingsession')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationViewAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_name', models.CharField(blank=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_views', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_audits', to='tracking.trackingsession')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['user', 'status'], name='tracking_tr_user_id_a88e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['emergency', 'status'], name='tracking_tr_emergen_9ac0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['started_at'], name='tracking_tr_started_cc7f30_idx'),
        ),
        migrations.AddIndex(
            model_name='routepoint',
            index=models.Index(fields=['session', 'recorded_at'], name='tracking_ro_session_1da328_idx'),
        ),
    ]
