# Generated by Django 6.0.6 on 2026-07-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerapikey',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='developerapikey',
            name='allowed_origins',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='developerapikey',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='developerapikey',
            name='rate_limit_per_minute',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='developerapikey',
            name='scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='developerapikey',
            name='webhook_url',
            field=models.URLField(blank=True),
        ),
    ]
