// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCudUCQZ64WJRYhAjni3epRH2MGBqELTWc',
    appId: '1:615379143825:web:c4e239a06fa49728bcc330',
    messagingSenderId: '615379143825',
    projectId: 'navigo-nigeria',
    authDomain: 'navigo-nigeria.firebaseapp.com',
    storageBucket: 'navigo-nigeria.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0i6Uu_JR2DAR_R4uo7V-foBoP_Xg4yOs',
    appId: '1:615379143825:android:c17bafa7ae8afb29bcc330',
    messagingSenderId: '615379143825',
    projectId: 'navigo-nigeria',
    storageBucket: 'navigo-nigeria.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2l6NX5qS13btMiSoSoHZWhVCX_D8ggZw',
    appId: '1:615379143825:ios:7bd613aff838181fbcc330',
    messagingSenderId: '615379143825',
    projectId: 'navigo-nigeria',
    storageBucket: 'navigo-nigeria.firebasestorage.app',
    iosClientId:
        '615379143825-44mgtgfs4ei1smq71lcbo79sfitt6t55.apps.googleusercontent.com',
    iosBundleId: 'com.psalmcodes.navigoLocate',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2l6NX5qS13btMiSoSoHZWhVCX_D8ggZw',
    appId: '1:615379143825:ios:7bd613aff838181fbcc330',
    messagingSenderId: '615379143825',
    projectId: 'navigo-nigeria',
    storageBucket: 'navigo-nigeria.firebasestorage.app',
    iosClientId:
        '615379143825-44mgtgfs4ei1smq71lcbo79sfitt6t55.apps.googleusercontent.com',
    iosBundleId: 'com.psalmcodes.navigoLocate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCudUCQZ64WJRYhAjni3epRH2MGBqELTWc',
    appId: '1:615379143825:web:dd2d5eb9a2f9a817bcc330',
    messagingSenderId: '615379143825',
    projectId: 'navigo-nigeria',
    authDomain: 'navigo-nigeria.firebaseapp.com',
    storageBucket: 'navigo-nigeria.firebasestorage.app',
  );
}
